# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2161ae3dced680ed93d92794cd21ecdea04a200234aa1c76f1fd0afa2caacfb1d0ec7f48d6bb440db33c043563e1ebe6a4685346fa9e6fe3641db20ccbeb9950

test:
  secret_key_base: ca350135f863125d9dc7eb56cd1b597a5505a7807f1597860a8e9c318454e295b987d7931e76e29fc8bd4d7907c8b80459e8073d3260f742a3bb53c1f20be0e1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
